Adding new prop-types library
frostney/react-intl-native pull request #11
Opened 2017-11-07 20:07 UTC by dustinsavery

React has deprecated PropTypes from the base library and created a separate package, `prop-types`. As of v 15.5 of React, PropTypes has been completely removed. (See [here](https://reactjs.org/docs/typechecking-with-proptypes.html))

2017-11-07 21:48 UTC, enterline requested changes

2017-11-07 21:48 UTC, enterline commented on package.json
> +    "prop-types": "^15.6.0",
This should be a dependency

2017-11-07 21:57 UTC, enterline approved these changes

2017-11-16 02:56 UTC, dustinsavery commented
@frostney Can we get this merged?

2017-11-24 12:56 UTC, kristerkari commented
I also need this in my project, so please merge this. :)

ping @frostney

2017-12-01 01:36 UTC, dustinsavery commented
@frostney Are you able to merge this? If you'd like, I can help manage this project so that we can keep up on top of PRs and issues.

2018-01-06 13:03 UTC, serhiipalash commented
Please merge this

2018-01-09 10:46 UTC, infostreams commented
I agree, it doesn't work without this pull request. Please merge this.

2018-01-09 11:07 UTC, infostreams commented
If you want to still use this library (@frostney it's BROKEN) use the following command:

`npm install git://github.com/changbenny/react-intl-native.git\#prop-types --save`

I get a different error message now (sigh), but at least the library itself is loading correctly.

2018-01-09 12:56 UTC, infostreams commented
Ok, whatever. It didn't work (at all) in my project and I needed it so I just did the changes myself. I opened a pull request (https://github.com/frostney/react-intl-native/pull/13) to merge these changes into this repository, but if you can't wait for that (like me), you can do

`npm install --save git://github.com/infostreams/react-intl-native.git`

and get going :-)

2018-01-09 14:32 UTC, serhiipalash commented
> so I just did the changes myself

I did the same :)
I guess soon we will create our from package to fix issues of this one )

2018-01-10 22:18 UTC, frostney commented
Apologies, I haven't had as much for open-source the past year as I'd like to have. Thank you so much for your efforts. ❤️ 
I'll cut a release today.

2018-01-10 22:20 UTC, frostney commented
P.S.: I'm totally open to add people as collaborators. Please let me know if anyone is interested.

2018-01-10 22:20 UTC, merged

2018-01-10 22:32 UTC, frostney commented
This has been published as `2.1.2`. Thank you again @dustinsavery and @enterline

2018-01-10 22:56 UTC, dustinsavery commented
@frostney 👏  Thanks